# Generated by Django 4.2.6 on 2023-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(upload_to='blog/static/images', verbose_name='Картинка статьи'),
        ),
    ]
