# Generated by Django 4.2.6 on 2023-11-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_fried'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendchat', to='blog.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userchat', to='blog.user')),
            ],
        ),
    ]
